In [ ]:
#install library

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

#set tampilan
pd.set_option('display.max_columns', None)
sns.set_theme(style='darkgrid')
print('Library berhasil diimport !!!')

Library berhasil diimport !!!

1. Collect Data

In [ ]:
#collect data

from google.colab import files
files.upload()

#pindah ke folder yang benar
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
print('kaggle API siap !!!')

Saving kaggle.json to kaggle.json
kaggle API siap !!!

In [ ]:
#conect dataset dari kaggle

!kaggle datasets download -d suhanigupta04/global-movies-dataset-19502026

#ekstrack file zip
import zipfile
with zipfile.ZipFile('global-movies-dataset-19502026.zip', 'r') as zip_ref:
    zip_ref.extractall('movies_data')


#cek isi folder
import os
print(os.listdir('movies_data'))

Dataset URL: https://www.kaggle.com/datasets/suhanigupta04/global-movies-dataset-19502026
License(s): CC0-1.0
Downloading global-movies-dataset-19502026.zip to /content
100% 4.79M/4.79M [00:01<00:00, 3.81MB/s]

['global_movies_dataset_1950_2026.csv']

In [ ]:
#Load dataset

df = pd.read_csv('movies_data/global_movies_dataset_1950_2026.csv')

print(f"shape : {df.shape}")
print(f"rows : {df.shape[0]:,} | Columns : {df.shape[1]}")
df.head()

shape : (100000, 27)
rows : 100,000 | Columns : 27

,movie_id,title,release_year,decade,runtime_min,genre,subgenre,director,lead_actor,lead_actress,country,language,imdb_rating,votes,budget_million,marketing_budget_million,revenue_million,roi_pct,popularity_score,metascore,audience_score,streaming_platform,award_nominations,award_wins,top_100_prob,blockbuster_flag,franchise_flag
0,1,Crimson Code,2001,2000,116,Action|Drama|Sci-Fi,Superhero,Denis Villeneuve,Brad Pitt,Tom Hanks,UK,Mandarin,7.0,15870,56.07,25.42,111.00,98.0,82.54,60,74,Netflix,3,2,0.560,0,0
1,2,Lost Empire,1951,1950,85,Crime|Animation,Gangster,Christopher Nolan,Scarlett Johansson,Brad Pitt,France,Mandarin,6.8,29639,45.29,31.19,108.38,139.3,80.54,64,56,MGM+,0,0,0.549,0,0
2,3,Last Legacy,1990,1990,141,Sci-Fi|Drama,Cyberpunk,Bong Joon-ho,Emma Stone,Brad Pitt,Japan,Japanese,6.2,19788,60.71,21.94,33.07,-45.5,81.98,59,60,Peacock,1,1,0.520,0,0
3,4,Crimson River,1952,1950,82,Mystery|Romance,Whodunit,Quentin Tarantino,Meryl Streep,Tom Hanks,France,German,6.3,11056,37.16,26.62,58.47,57.4,72.10,69,77,Disney+,1,1,0.498,0,0
4,5,Lost Dream,2011,2010,130,Romance,Romantic Drama,Quentin Tarantino,Robert Downey Jr.,Timothee Chalamet,Germany,English,5.6,12505,19.78,6.23,39.13,97.8,60.63,48,57,Prime Video,0,0,0.435,0,0

2. Exploration data analysis

In [ ]:
#info tipe data dan missing value
print("=" * 50)
print("Info Dataset")
print("=" * 50)
df.info()

==================================================
Info Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   movie_id                  100000 non-null  int64
 1   title                     100000 non-null  object
 2   release_year              100000 non-null  int64
 3   decade                    100000 non-null  int64
 4   runtime_min               100000 non-null  int64
 5   genre                     100000 non-null  object
 6   subgenre                  100000 non-null  object
 7   director                  100000 non-null  object
 8   lead_actor                100000 non-null  object
 9   lead_actress              100000 non-null  object
 10  country                   100000 non-null  object
 11  language                  100000 non-null  object
 12  imdb_rating               100000 non-null  float64
 13  votes                     100000 non-null  int64
 14  budget_million            100000 non-null  float64
 15  marketing_budget_million  100000 non-null  float64
 16  revenue_million           100000 non-null  float64
 17  roi_pct                   100000 non-null  float64
 18  popularity_score          100000 non-null  float64
 19  metascore                 100000 non-null  int64
 20  audience_score            100000 non-null  int64
 21  streaming_platform        100000 non-null  object
 22  award_nominations         100000 non-null  int64
 23  award_wins                100000 non-null  int64
 24  top_100_prob              100000 non-null  float64
 25  blockbuster_flag          100000 non-null  int64
 26  franchise_flag            100000 non-null  int64
dtypes: float64(7), int64(11), object(9)
memory usage: 20.6+ MB

In [ ]:
from pandas._libs import missing
print("=" * 50)
print("Missing Value")
print("=" * 50)

missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({
    "Missing_Count" : missing,
    "Missing %" : missing_pct
}).query('Missing_Count > 0').sort_values('Missing %', ascending=False)

if missing_df.empty:
    print("Tidak ada missing value")
else:
    print(missing_df)

==================================================
Missing Value
==================================================
Tidak ada missing value

In [ ]:
print("=" * 50)
print('Statistik Deskriptif')
print("="*50)

df.describe().round(2)

==================================================
Statistik Deskriptif
==================================================

,movie_id,release_year,decade,runtime_min,imdb_rating,votes,budget_million,marketing_budget_million,revenue_million,roi_pct,popularity_score,metascore,audience_score,award_nominations,award_wins,top_100_prob,blockbuster_flag,franchise_flag
count,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00
mean,50000.50,1988.01,1983.64,113.71,6.74,40204.26,48.27,22.97,133.31,176.87,80.08,66.72,69.74,1.65,0.59,0.55,0.23,0.18
std,28867.66,22.22,22.27,20.22,1.01,52127.49,43.58,24.09,196.40,238.86,10.17,15.46,14.03,2.02,1.00,0.07,0.42,0.38
min,1.00,1950.00,1950.00,70.00,2.20,425.00,0.50,0.10,0.06,-90.00,33.84,10.00,12.00,0.00,0.00,0.22,0.00,0.00
25%,25000.75,1969.00,1960.00,100.00,6.10,12440.00,16.07,6.32,24.42,14.80,73.18,56.00,60.00,0.00,0.00,0.50,0.00,0.00
50%,50000.50,1988.00,1980.00,114.00,6.70,24305.00,34.86,14.96,66.15,100.90,80.16,67.00,70.00,1.00,0.00,0.55,0.00,0.00
75%,75000.25,2007.00,2000.00,127.00,7.40,47767.25,68.00,31.01,159.56,253.92,87.26,77.00,79.00,2.00,1.00,0.60,0.00,0.00
max,100000.00,2026.00,2020.00,205.00,9.80,1539859.00,284.42,180.00,2940.58,1100.60,100.00,100.00,100.00,17.00,9.00,0.94,1.00,1.00

In [ ]:
#cek distribusi imb rating

fig = px.box(
    df,
    x = 'decade',
    y = 'imdb_rating',
    color = 'decade',
    title = 'Distribusi IMDb Rating per Dekade',
    labels={'decade' : 'Dekade', 'imdb_rating' : 'IMDb Rating'},
    template='plotly_dark'
)

fig.update_layout(showlegend=False)
fig.show()

In [ ]:
#genre paling populer

#genre perlu dipecah karena format "Action|Drama|Sci-Fi"
genre_split = df['genre'].str.split('|').explode()
genre_counts = genre_split.value_counts().reset_index()
genre_counts.columns = ['genre', 'count']

fig = px.bar(
    genre_counts.head(15),
    x = 'count',
    y = 'genre',
    orientation='h',
    color = 'count',
    title = 'Top 15 genre populer',
    labels={'count' : 'Jumlah Film', 'genre' : 'Genre'},
    color_continuous_scale = 'viridis',
    template = 'plotly_dark'
    )

fig.update_layout(yaxis = {'categoryorder' : 'total ascending'})
fig.show()

In [ ]:
from plotly.graph_objs import XAxis
#Tren Budget vs Revenue per Tahun


yearly = df.groupby('release_year').agg(
    avg_budget = ('budget_million', 'mean'),
    avg_revenue = ('revenue_million', 'mean')
).reset_index()

fig = make_subplots(specs=[[{"secondary_y": False}]])

fig.add_trace(go.Scatter(
    x=yearly['release_year'], y=yearly['avg_budget'], name='Average Budget ($M)', line=dict(color='#f39c12', width=2)
))

fig.add_trace(go.Scatter(
    x = yearly['release_year'], y=yearly['avg_revenue'], name = 'Avg Revenue ($M)', line=dict(color = '#2ecc71', width=2)
))

fig.update_layout(
    title='Tren rata rata tahunan vs revenue per tahun',
    xaxis_title = 'Tahun',
    yaxis_title = 'Nilai ($ Juta)',
    template = 'plotly_dark',
    hovermode = 'x unified'
)

fig.show()